# Generated by Django 5.2.4 on 2025-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textsfortest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('parenttext', models.CharField(default='', max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
