# Generated by Django 5.2.4 on 2025-07-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsfortest',
            name='id',
        ),
        migrations.AlterField(
            model_name='textsfortest',
            name='text',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textsfortest',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
