# Generated by Django 5.2.4 on 2025-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_remove_textsfortest_id_alter_textsfortest_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsfortest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textsfortest',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
