# Generated by Django 5.2.4 on 2025-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_textsfortest_id_alter_textsfortest_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsfortest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
